### PR TITLE
Data primer

### PR DESCRIPTION
**Pull request by Talv**
Continuation of #4

### CODE REVIEW

**Comment by Talv** [comment]
@duckiesduckies I've fixed some stuff but got bored half way through. Anyway it's good as it is (formatting can be improved in further commits)

Feel free to merge this and see the magic happen
image

**Comment by Talv** [comment]
This is how it looked before my fixes:
screencapture-127-0-0-1-8001-New-Tutorials-07-Lessons-Data-Primer-1-Simple-Firebolt-2022-01-11-16_25_28

**Comment by Talv** [comment]
This is how it looked after:
screencapture-127-0-0-1-8001-Data-Primer-01-Simple-Firebolt-01-Firebolt-2022-01-11-17_05_13

**Comment by duckiesduckies** [comment]
> @duckiesduckies I've fixed some stuff but got bored half way through. Anyway it's good as it is (formatting can be improved in further commits)
> 
> Feel free to merge this and see the magic happen image

Can you believe I couldn't find the "Merge pull request" thing because it was a the bottom of comments under huge image, but I was frantically looking for it at the top like a fool :D.

Anyway, if I merge this pull request - it'll update the live website. Is there a way to preview end result just like you showed in these screenshots? Or do you have some sort of duplicate repo where you are able to create a copy?

.. wait, am I able to do that too? I have no idea how to. Do I need to sacrifice goats for it?

Hold on, I've just noticed "Site generator. We're using [mkdocs.org].".. I'm afraid to look.

**Pull request merged**
