### PR TITLE
Fix filenames

### PR DESCRIPTION
**Pull request by nudefireninja**
Good day!

I fixed a bunch of **images that were in the wrong order**. (and some minor tweaks to captions headings mostly) This affected only chapters with 10 or more images (though not all -- mostly the problems were in the Terrain, and Trigger Editor chapters).

_Sorry if my pull request isn't following the latest git conventions or best practices, I don't do this sort of thing very often, but I welcome any criticisms you may have._

P.S. While I was doing this, I noticed a few other problems that I wasn't sure how to fix because some images seemed to just be missing, or the text wasn't clear. They are: **01_Introduction/013_Standard_Dependencies.md**, **03_Trigger_Editor/032_Trigger_Editor_Introduction.md**, **04_Data_Editor/062_Range_Actors.md** (the section on Range Actor Types).

### CODE REVIEW

**Comment by abrahamYG** [comment]
Thanks a ton for the contributions! This repo definitely needed some love that required time many of us are lacking atm. Give just a chance to review and will see to merge or provide feedback if needed.

**Comment by nudefireninja** [comment]
Great!

But uh-oh, it looks like GitHub is interpreting the renames as binary changes. I thought that would be avoided by renaming the files over 2 commits (which did show up as only renames on my computer). Do you think it's a problem?

**Comment by abrahamYG** [comment]
I see that on your first commit they got identified as just renamed, but the second commit probably had additional changes (tbh could be just metadata like last modified fields, etc). I will need to deploy locally to review

**Comment by nudefireninja** [comment]
Okay. For me it does show only as renames if I view each commit inidividually, but I guess when it compares against master it shows them as changed.

**Review by abrahamYG — APPROVED** [review]

**Pull request merged**
